import type { Metadata } from 'next'
import './styles.css'
// import { PostHogProvider } from '@/components/providers/posthog-provider'
import ThemeProvider from '@/components/theme-provider'
import { GoogleTagManager, GoogleTagManagerNoScript } from '@/services/gtm'
import { fonts } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* <PostHogProvider> */}
      <head>
        <GoogleTagManager />
      </head>
      <body className={`${fonts} antialiased`}>
        <GoogleTagManagerNoScript />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
      {/* </PostHogProvider> */}
    </html>
  )
}
