import type { Metadata } from 'next'
import './styles.css'
import { CookieBanner } from '@/components/cookie-banner'
import { PostHogProvider } from '@/components/providers/posthog-provider'
import { fonts } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <PostHogProvider>
        <body className={`${fonts} antialiased`}>
          {children}
          <CookieBanner />
        </body>
      </PostHogProvider>
    </html>
  )
}
